-- Credit Card Management System - Oracle Database schema

CREATE TABLE customer (
    customer_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(100 CHAR) NOT NULL,
    email_address VARCHAR2(320 CHAR) NOT NULL,
    mobile_number VARCHAR2(20 CHAR)  NOT NULL,
    pan_number    VARCHAR2(10 CHAR)  NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_email UNIQUE (email_address),
    CONSTRAINT uq_customer_mobile UNIQUE (mobile_number),
    CONSTRAINT uq_customer_pan UNIQUE (pan_number),
    CONSTRAINT ck_customer_pan_format
        CHECK (REGEXP_LIKE(pan_number, '^[A-Z]{5}[0-9]{4}[A-Z]$'))
);

CREATE TABLE credit_card (
    card_number        VARCHAR2(19 CHAR) NOT NULL,
    customer_id        NUMBER(19)        NOT NULL,
    card_type          VARCHAR2(10 CHAR) NOT NULL,
    credit_limit       NUMBER(15,2)      NOT NULL,
    available_credit   NUMBER(15,2)      NOT NULL,
    outstanding_amount NUMBER(15,2)      DEFAULT 0 NOT NULL,
    expiry_date        DATE              NOT NULL,
    card_status        VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_credit_card PRIMARY KEY (card_number),
    CONSTRAINT fk_card_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT ck_card_number_format
        CHECK (REGEXP_LIKE(card_number, '^[0-9]{16,19}$')),
    CONSTRAINT ck_card_type
        CHECK (card_type IN ('SILVER', 'GOLD', 'PLATINUM')),
    CONSTRAINT ck_card_status
        CHECK (card_status IN ('ACTIVE', 'BLOCKED')),
    CONSTRAINT ck_card_amounts
        CHECK (
            credit_limit > 0
            AND available_credit >= 0
            AND available_credit <= credit_limit
            AND outstanding_amount >= 0
            AND outstanding_amount <= credit_limit
            AND available_credit + outstanding_amount = credit_limit
        )
);

CREATE TABLE merchant (
    merchant_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    merchant_name VARCHAR2(150 CHAR) NOT NULL,
    category      VARCHAR2(100 CHAR) NOT NULL,
    location      VARCHAR2(200 CHAR) NOT NULL,
    CONSTRAINT pk_merchant PRIMARY KEY (merchant_id)
);

-- Do not call this table TRANSACTION: it is an Oracle SQL keyword.
CREATE TABLE card_transaction (
    transaction_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    card_number      VARCHAR2(19 CHAR) NOT NULL,
    transaction_type VARCHAR2(10 CHAR) NOT NULL,
    amount           NUMBER(15,2)      NOT NULL,
    merchant_id       NUMBER(19),
    transaction_time  TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    status            VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT pk_card_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT fk_transaction_card FOREIGN KEY (card_number)
        REFERENCES credit_card (card_number),
    CONSTRAINT fk_transaction_merchant FOREIGN KEY (merchant_id)
        REFERENCES merchant (merchant_id),
    CONSTRAINT ck_transaction_type
        CHECK (transaction_type IN ('PURCHASE', 'PAYMENT')),
    CONSTRAINT ck_transaction_amount CHECK (amount > 0),
    CONSTRAINT ck_transaction_status
        CHECK (status IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_transaction_merchant
        CHECK (
            (transaction_type = 'PURCHASE' AND merchant_id IS NOT NULL)
            OR (transaction_type = 'PAYMENT' AND merchant_id IS NULL)
        )
);

-- Foreign-key and reporting indexes.
CREATE INDEX idx_credit_card_customer ON credit_card (customer_id);
CREATE INDEX idx_transaction_card_time ON card_transaction (card_number, transaction_time);
CREATE INDEX idx_transaction_merchant ON card_transaction (merchant_id);
CREATE INDEX idx_transaction_type_time ON card_transaction (transaction_type, transaction_time);

COMMENT ON TABLE card_transaction IS
    'Audit trail for both successful and failed purchases and payments.';
COMMENT ON COLUMN card_transaction.merchant_id IS
    'Required for purchases and null for payments.';
